<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite Account" duration-ms="137924" started-at="2012-08-16T10:09:20Z" finished-at="2012-08-16T10:11:38Z">
    <groups>
      <group name="Account">
        <method signature="Test_PLT_ACC_010.testPLT_ACC_010()[pri:0, instance:org.exoplatform.Selenium.platform.eXoGTN.Account.Test_PLT_ACC_010@144aa0ce]" name="testPLT_ACC_010" class="org.exoplatform.Selenium.platform.eXoGTN.Account.Test_PLT_ACC_010"/>
      </group> <!-- Account -->
    </groups>
    <test name="Test Account 010" duration-ms="137924" started-at="2012-08-16T10:09:20Z" finished-at="2012-08-16T10:11:38Z">
      <class name="org.exoplatform.Selenium.platform.eXoGTN.Account.Test_PLT_ACC_010">
        <test-method status="FAIL" signature="testPLT_ACC_010()[pri:0, instance:org.exoplatform.Selenium.platform.eXoGTN.Account.Test_PLT_ACC_010@144aa0ce]" name="testPLT_ACC_010" duration-ms="137871" started-at="2012-08-16T17:09:20Z" finished-at="2012-08-16T17:11:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Timeout at waitForElementPresent: //a[@text='Group and Roles']]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Timeout at waitForElementPresent: //a[@text='Group and Roles']
	at org.testng.Assert.fail(Assert.java:89)
	at org.exoplatform.Selenium.Common.CommonHelpers.waitForAndGetElement(CommonHelpers.java:109)
	at org.exoplatform.Selenium.Common.CommonHelpers.mouseOverAndClick(CommonHelpers.java:409)
	at org.exoplatform.Selenium.Common.CommonHelpers.goToPage(CommonHelpers.java:316)
	at org.exoplatform.Selenium.UserManagementHelpers.goToUsersAndGroupsManagement(UserManagementHelpers.java:43)
	at org.exoplatform.Selenium.platform.eXoGTN.Account.Test_PLT_ACC_010.testPLT_ACC_010(Test_PLT_ACC_010.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPLT_ACC_010 -->
      </class> <!-- org.exoplatform.Selenium.platform.eXoGTN.Account.Test_PLT_ACC_010 -->
    </test> <!-- Test Account 010 -->
  </suite> <!-- Suite Account -->
</testng-results>
